# Generated by Django 5.0.6 on 2024-05-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartmodel",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="cartmodel",
            name="category",
        ),
        migrations.RemoveField(
            model_name="cartmodel",
            name="featured",
        ),
        migrations.RemoveField(
            model_name="cartmodel",
            name="rating",
        ),
    ]
